DP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cafe/", include("cafe.urls")),
    path("users/", include("users.urls")),
]

users/urls.py
from django.urls import path
from users import views

app_name = "users"
urlpatterns = [
    path("feedback/", views.feedback, name = "feedback"),
    path("feedback_delete/<int:feedback_id>/", views.feedback_delete, name="feedback_delete"),
    path("feedback_edit/<int:feedback_id>/", views.feedback_edit, name="feedback_edit"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from cafe.models import Menu

# Create your models here.
class User(AbstractUser):
    nickname = models.CharField("닉네임", max_length=10)

class Like(models.Model):
    user_id = models.ForeignKey("users.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    menu_id = models.ForeignKey(Menu,
                             verbose_name="메뉴",
                             on_delete=models.CASCADE)
    
class Post(models.Model):
    user_id = models.ForeignKey("users.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    title = models.CharField("제목", max_length=20)
    contents = models.TextField("내용", blank=True)

users/forms.py
from django import forms
from users.models import Post, User
from django.core.exceptions import ValidationError

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "contents",
        ]
        widgets = {
            "contents": forms.Textarea(
                attrs={
                    "placeholder": "건의 사항....",
                }
            )
        }

class LoginForm(forms.Form):
    username = forms.CharField(
        min_length = 3,
        widget=forms.TextInput(
            attrs={"placeholder": "사용자명 (3자리 이상)"},
        ),
    )
    password = forms.CharField(
        min_length = 4,
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호 (4자리 이상)"}
        ),
    )

class SignupForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data["username"]

        if User.objects.filter(username=username).exists():
            raise ValidationError(f"입력한 사용자명({username})은 이미 사용 중 입니다")
        
        return username
    
    def clean(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 != password2:
            self.add_error("password2", "비밀번호와 비밀번호 확인란의 값이 다릅니다")

    def save(self):
        username = self.cleaned_data["username"]
        password1 = self.cleaned_data["password1"]


        user = User.objects.create_user(
            username = username,
            password = password1,
        )
        return user

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth import authenticate, login, logout

from users.forms import PostForm, LoginForm, SignupForm
from users.models import Post, User

# Create your views here.

# 건의사항 페이지
def feedback(request):
    if request.method == "POST":
        form = PostForm(request.POST)

        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.user_id = request.user
            feedback.save()
    else:
        form = PostForm()

    feedbacks = Post.objects.all()
    context = {
        "feedbacks": feedbacks,
        "form" : form,
    }
    return render(request, "feedback.html", context)

# 건의사항 삭제
def feedback_delete(request, feedback_id):
    Post.objects.filter(id=feedback_id).delete()
    return redirect("users:feedback")

# 건의사항 수정
def feedback_edit(request, feedback_id):
    feedback = get_object_or_404(Post, id = feedback_id)
    if request.method == "POST":
        form = PostForm(request.POST, instance=feedback)
        if form.is_valid():
            feedback = form.save(commit = False)
            feedback.save()
            return redirect("users:feedback")
        
    else:
        form = PostForm(instance = feedback) # 수정 대상이 될 데이터를 설정
    return render(request, "feedback_edit.html", {"form" : form})

def login_view(request):
    # 이미 로그인되어 있는 경우
    if request.user.is_authenticated:
        return redirect("cafe:main")
    
    if request.method == "POST":
        # LoginForm 인스턴스를 만들며, 입력 데이터는 request.POST 를 사용
        form = LoginForm(data=request.POST)

        # # LoginForm 에 들어온 데이터가 적절한지 유효성 검사
        # print("form.is_valid():", form.is_valid())

        # # 유효성 검사 이후에는 cleaned_data 에서 데이터를 가져와 사용
        # print("form.cleaned_data:", form.cleaned_data)

        # LoginForm 에 전달된 데이터가 유효하다면
        if form.is_valid():
            # username과 password 값을 가져와 변수에 할당
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # username, password 에 해당하는 사용자가 있는지 검사
            user = authenticate(username=username, password=password)

            # 해당 사용자가 존재한다면
            if user:
                # 로그인 처리 후, 메인 페이지로 redirect
                login(request, user)
                return redirect("cafe:main")

            # 해당 사용자가 없다면 form에 에러 추가
            else:
                form.add_error(None, "해당하는 사용자가 없습니다")

        # 어떤 이유든, 실패한 경우라면 다시 LoginForm 을 사용한 로그인 페이지 렌더링
        context = {
            "form": form,
        }
        return render(request, "login.html", context)

    else:
        form = LoginForm()

        context = {
            "form": form,
        }
        return render(request, "login.html", context)
    
def logout_view(request):
    # logout 함수 호출에 request를 전달
    logout(request)

    # logout 처리 후, 로그인페이지로 이동
    return redirect("users:login")

def signup(request):
    if request.method == "POST":
        form = SignupForm(data=request.POST)

        # Form에 에러가 없다면 form의 save() 메서드로 사용자를 생성
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("users:login")
    
    # GET 요청에서는 빈 Form을 보여줌
    else:
        # SignupForm 인스턴스를 생성, Template에 전달
        form = SignupForm()

    # context로 전달되는 form 은 두 가지 경우가 존재
    # 1. POST 요청에서 생성된 form 이 유효하지 않은 경우
    # --> 에러를 포함한 form이 사용자에게 보여짐
    # 2. GET 요청으로 빈 form이 생성된 경우
    # --> 빈 form이 사용자에게 보여짐
    context = {"form" : form}
    return render(request, "signup.html", context)

users/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

users/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>건의사항</h1>
    <div class="feddback">
        {% for feedback in feedbacks %}
            <h3>{{ feedback.title }}</h1>
            <p>{{ feedback.contents }}</p>
            {% if user == feedback.user_id %}
            <form method="POST" action="{% url 'users:feedback_delete' feedback_id=feedback.id %}">
                {% csrf_token %}
                <button type="submit">삭제</button>
            </form>
            <form action="{% url 'users:feedback_edit' feedback_id=feedback.id %}">
                <button type="submit">수정</button>
            </form>
            {% endif %}
        {% endfor%}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">게시</button>
        </form>
    </div>
</body>
</html>

users/templates/feedback_edit.html
<!DOCTYPE html>
<html lang="ko">
    <body>
        {{ form.as_p }}
    </body>
</html>

users/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div id="login">
    <form method="POST">
        <h1>드링크픽커스</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-login">로그인</button>
        <a href="{% url 'users:signup' %}">회원가입 페이지로 이동</a> 
    </form>
</div>
{% endblock %}

users/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div id="signup">
    <form method="POST" enctype="multipart/form-data">
        <h1>카페 회원가입</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-signup">회원가입</button>
        <a href="{% url 'users:login' %}">로그인 페이지로 이동</a>
    </form>
</div>
{% endblock %}