DP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cafe/", include("cafe.urls")),
    path("users/", include("users.urls")),
]

cafe/urls.py
from django.urls import path
from cafe import views

app_name = "cafe"
urlpatterns = [
    path("menu/<int:menu_id>/", views.menu_detail, name = "detail" ),
    path("main/", views.main, name="main"),
    path("menu/<int:menu_id>/like/", views.menu_like, name='like'), 
    path("comment_add/<int:id>/", views.comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>", views.comment_delete, name="comment_delete"),
]

cafe/models.py
from django.db import models

# Create your models here.
class Menu(models.Model):
    brand = models.CharField("브랜드", max_length=10)
    category = models.CharField("카테고리", max_length=5)
    coffee_name = models.CharField("이름", max_length=50)
    protein = models.FloatField("단백질", blank=True)
    calorie = models.FloatField("칼로리", blank=True)
    fatty = models.FloatField("포화지방", blank=True)
    na = models.FloatField("나트륨", blank=True)
    dang = models.FloatField("당류", blank=True)
    caffeine = models.FloatField("카페인", blank=True)
    img = models.CharField("이미지", max_length=200)

class Comment(models.Model):
    user_id = models.ForeignKey("users.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    menu_id = models.ForeignKey(Menu,
                             verbose_name="메뉴",
                             on_delete=models.CASCADE)
    content = models.TextField("내용", blank=True)
    created = models.DateTimeField("작성일시", auto_now_add=True)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from cafe.models import Menu

# Create your models here.
class User(AbstractUser):
    nickname = models.CharField("닉네임", max_length=10)

class Like(models.Model):
    user_id = models.ForeignKey("users.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    menu_id = models.ForeignKey(Menu,
                             verbose_name="메뉴",
                             on_delete=models.CASCADE)
    
class Post(models.Model):
    user_id = models.ForeignKey("users.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    title = models.CharField("제목", max_length=20)
    contents = models.TextField("내용", blank=True)

cafe/forms.py
from cafe.models import Comment
from django import forms

class CommentForm(forms.ModelForm): 
    class Meta: 
        model = Comment
        fields = [ 
            "content",
            "menu_id"
        ]
        widgets = {
            "content" : forms.Textarea(
                attrs={
                    "placeholder" : "댓글 달기..."
                }
            )
        }

cafe/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.http import HttpResponseForbidden

from users.models import Like
from cafe.models import Menu, Comment
from cafe.forms import CommentForm

# Create your views here.

def menu_detail(request, menu_id): 

    menu = Menu.objects.get(id = menu_id)
    comment_form = CommentForm()

    context = {
        "menu" : menu, 
        "comment_form" : comment_form,
    }

    return render(request, "menu_detail.html", context)

@require_POST
def menu_like(request, menu_id) : 
    menu = Menu.objects.get(id = menu_id)    
    user = request.user # 좋아요 한 사람

    if request.method == "POST": 
        if Like.objects.filter(menu_id=menu_id, user_id=user.id).exists():
            Like.objects.filter(menu_id=menu_id, user_id=user.id).delete()

        else: 
            Like.objects.create(
                menu_id = menu, 
                user_id = user,
            )

        return redirect("cafe:detail", menu_id=menu_id)


@require_POST
def comment_add(request, id):
    # request.POST 로 전달된 데이터를 사용해 CommentForm 인스턴스를 생성
    form = CommentForm(data=request.POST)

    if form.is_valid():
        # comment=False 옵션으로 메모리상에 Comment 객체 생성
        comment = form.save(commit=False)

        #Comment 생성에 필요한 사용자 정보를 request 에서 가져와 할당
        comment.user_id = request.user # request.user : 현재 접속을 한 유저

        # DB 에 comment 객체 저장
        comment.save()
        return redirect("cafe:detail", menu_id=id)

@require_POST
def comment_delete(request, comment_id): 
    comment = Comment.objects.get(id=comment_id)

    if comment.user == request.user: 
        comment.delete()

        url = reverse("posts:feeds") + f"#post-{comment.post.id}"
        return redirect(url)
    
    else: 
        return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")
 


# Create your views here.
def main(request):
    if request.method == "POST":
        brand = request.POST.get("brand")
        category = request.POST.get("category")
        order_by = request.POST.get("order_by")

        if brand == "기본" and category == "기본":
            menus = Menu.objects.all()
        elif brand == "기본":
            menus = Menu.objects.filter(category=category)    
        elif category == "기본":
            menus = Menu.objects.filter(brand=brand)
        else:
            menus = Menu.objects.filter(brand=brand, category=category)

        if order_by != "기본":
            menus = Menu.objects.order_by(order_by)
    else:
        menus = Menu.objects.all()
    
    context = {
        "menus": menus
    }
    return render(request, "main.html", context)

cafe/templates/main.html
<!DOCTYPE html>
<html lang="en">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link rel="stylesheet" href="/static/CSS/main.css">
    <link rel="stylesheet" href="/static/CSS/reset.css">
    <body>

        <header>
            <div class="digital">
                <div class="hours">00</div>
                <div class="minutes">00</div>
                <div class="seconds">00</div>
            </div>
            <nav>
                <ul>
                <li>
                    <label for="h"><a href="#home">main</a></label>
                </li>
                <li>
                    <label for="a"><a href="#about">about</a></label>
                </li>
                <li>
                    <label for="s"><a href="#skills">skills</a></label>
                </li>
                </li>
                </ul>
            </nav>
            <div class="login-sign">
                <a href=""><p>Login</p></a>
                <a href=""><p>Sign</p></a>
            </div>
        </header>

        <div class="swiper mySwiper">
            <div class="swiper-wrapper">
                <div class="swiper-slide">

                    <div class="swiper-image">
                        <a href=""><img src="https://paikdabang.com/wp-content/uploads/2018/06/%EB%AF%B8%EC%88%AB%EA%B0%80%EB%A3%A8-450x588.png"></a>
                        <p>아이스티</p>
                        <span>인기</span>
                    </div>

                    <div class="swiper-image">
                        <img src="https://paikdabang.com/wp-content/uploads/2018/06/%EC%B2%AD%ED%8F%AC%EB%8F%84%EC%97%90%EC%9D%B4%EB%93%9C-450x588.png">
                        <p>커피</p>
                        <span>인기</span>
                    </div>

                    <div class="swiper-image">
                        <img src="https://paikdabang.com/wp-content/uploads/2021/12/%EC%99%84%EC%A0%84%ED%86%A0%EB%A7%88%ED%86%A0-450x588.png">
                        <p>쉐이크</p>
                        <span>인기</span>
                    </div>
                </div>
        
                <div class="swiper-slide">
                    <div class="swiper-image">
                        <img src="https://paikdabang.com/wp-content/uploads/2021/12/%EC%99%84%EC%A0%84%ED%86%A0%EB%A7%88%ED%86%A0-450x588.png">
                        <p>아이스티</p>
                        <span>인기</span>
                    </div>

                    <div class="swiper-image">
                        <img src="https://paikdabang.com/wp-content/uploads/2021/12/%EC%99%84%EC%A0%84%ED%86%A0%EB%A7%88%ED%86%A0-450x588.png">
                        <p>커피</p>
                        <span>인기</span>
                    </div>

                    <div class="swiper-image">
                        <img src="https://paikdabang.com/wp-content/uploads/2021/12/%EC%99%84%EC%A0%84%ED%86%A0%EB%A7%88%ED%86%A0-450x588.png">
                        <p>쉐이크</p>
                        <span>인기</span>
                    </div>
                </div>
            </div>
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
        </div>
        <div class="category">
            <form method="POST" action="{% url 'cafe:main' %}">
            {% csrf_token %}
                <label for="brand">브랜드</label>
                <select name="brand" id="brand">
                    <option value="기본">기본</option>
                    <option value="스타벅스">스타벅스</option>
                    <option value="메가커피">메가커피</option>
                    <option value="이디야">이디야</option>
                    <option value="바나프레소">바나프레소</option>
                </select>
            
                <label for="category">카테고리</label>
                <select name="category" id="category">
                    <option value="기본">기본</option>
                    <option value="커피">커피</option>
                    <option value="음료">음료</option>
                    <option value="스무디">스무디</option>
                    <option value="티">티</option>
                </select>
                
                <label for="order_by">정렬</label>
                <select name="order_by" id="order_by">
                    <option value="기본">기본</option>
                    <option value="-caffeine">카페인 ▲</option>
                    <option value="caffeine">카페인 ▼</option>
                    <option value="-calorie">칼로리 ▲</option>
                    <option value="calorie">칼로리 ▼</option>
                    <option value="-dang">당류 ▲</option>
                    <option value="dang">당류 ▼</option>
                    <option value="-protein">단백질 ▲</option>
                    <option value="protein">단백질 ▼</option>
                </select>

                <button type="submit">검색</button>
            </form>
        </div>
        
        <div class="grid">
            {% for menu in menus %}
            <div class="coffee">
                <a href="{% url 'cafe:detail' menu_id=menu.id %}"><h1>{{ menu.coffee_name }}</h1></a>
                <div class="category_brand">
                    <h2 
                    {% if menu.category in "커피" %}
                        style="background-color: rgb(196, 179, 94);"
                    {% elif menu.category in "음료"%}
                        style="background-color: rgb(172, 236, 172);"
                    {% elif menu.category in "티"%}
                        style="background-color: rgb(255, 249, 169);"
                    {% elif menu.category in "스무디"%}
                        style="background-color: rgb(245, 160, 81);"
                    {% endif %}>{{ menu.category }}</h2>
                    <h2 
                    {% if menu.brand in "스타벅스" %}
                        style="background-color: rgb(49, 160, 99);"
                    {% elif menu.brand in "메가커피"%}
                        style="background-color: rgb(172, 236, 172);"
                    {% elif menu.brand in "이디야"%}
                        style="background-color: rgb(230, 221, 97);"
                    {% elif menu.brand in "바나프레소"%}
                        style="background-color: rgb(240, 252, 133);"
                    {% endif %}>{{ menu.brand }}</h2>
                </div>
                <a href="{% url 'cafe:detail' menu_id=menu.id %}"><img src="{{ menu.img }}"></a>
                <div class="kcal_table">
                    <div class="kcal">
                        <div>
                            <p>카페인(mg)</p> 
                            <p>{{ menu.caffeine }}</p>
                        </div>
                        <div>
                            <p>칼로리(kcal)</p> 
                            <p>{{ menu.calorie }}</p>
                        </div>
                        <div>
                            <p>포화지방</p> 
                            <p>{{ menu.fatty }}</p>
                        </div>
                    </div>
                    <div class="kcal kcal2">
                        <div>
                            <p>단백질(g)</p> 
                            <p>{{ menu.protein }}</p>
                        </div>
                        <div>
                            <p>당류(g)</p> 
                            <p>{{ menu.dang }}</p>
                        </div>
                        <div>
                            <p>나트륨(mg)</p> 
                            <p>{{ menu.na }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </body>

    <footer>
        <div class="reference">
            <!-- <img src="./images/Disney_Plus_logo.svg.png" alt=""> -->
            <ul>
                <i class='bx bx-globe'></i>
                <li>
                    <select name="" id="">
                        <option value="">
                            한국어 
                        </option>
                        <option value="">English</option>
                    </select>
                </li>
                <li><a href="#">디즈니+이용약관</a></li>
                <li><a href="#">개인정보 처리 방침</a></li>
                <li><a href="#">개인정보 처리방침 부속서</a></li>
                <li><a href="#">관심 기반 광고</a></li>
                <li><a href="#">고객센터</a></li>
                <li><a href="#">다양한 시청 방법</a></li>
                <li><a href="#">디즈니+ 소개</a></li>
                <li><a href="#">통신판매업 사업자정보확인</a></li>
            </ul>
            <p>
                <address>
                    월트디즈니컴퍼니코리아 유한책임회사 | 대표자: 김소연 | 서울특별시 강남구 테헤란로 152, 7층 (우편번호: 06236) | Email: help@disneyplus.kr | 연락처: 080 822 1416 | 사업자등록번호: 220-81-03347 | 통신판매업 신고번호: 제2021-서울강남-05456호 |<br>
                    비디오물배급업 신고번호: 제2016-16호 | 호스팅서비스 사업자: NSOne
                </address>
            </p>
            <p>
                디즈니+의 콘텐츠는 서비스 여부에 따라 달라질 수 있습니다.<br>
                © 2023 Disney and its related entities. All Rights Reserved.
            </p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script src="/static/Script/main.js"></script>
</html>

cafe/templates/menu_detail.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <title>{{ menu.coffee_name }}</title>
    </head>
    <!-- 메뉴 상세 -->
    <body>
        <div class="cafe-menu">
            <h1> {{ menu.coffee_name }} </h1>
            <img src = "{{ menu.img }}">
            <h2> {{ menu.brand }}</h2>
            <p>단백질 : {{ menu.protein }}</p>
            <p>칼로리 : {{ menu.calorie }}</p>
            <p>포화지방 : {{ menu.fatty }}</p>
            <p>나트륨 : {{ menu.na }}</p>
            <p>당류 : {{ menu.dang }}</p>
            <p>카페인 : {{ menu.caffeine }}</p>   
        </div>
    
    <!-- 좋아요/ 댓글 시작 -->
        <div>
            <form action="{% url 'cafe:detail' menu_id=menu.id %}like/" method="POST" >
                {% csrf_token %}
                <button type="submit">
                    <!-- Menu에 좋아요 누른 사용자 수를 가져옴-->
                    Likes({{ menu.like_set.count }})
                </button>
            </form>
        <span>Comments({{ menu.comment_set.count }})</span>

        {% for comment in menu.comment_set.all %}
            <h4>{{ comment.user_id }}</h4>
            <p> {{ comment.content }}</p>
        {% empty %}
            <li> 아직 댓글이 없습니다 </li>
        {% endfor %}
        </div>
        </div>
    <!-- 댓글 달기 -->
        <div>


        </div>
    </body>
</html>